baseURL = "http://mikebenfield.github.io/"
languageCode = "en-us"
title = "Michael Benfield's blog"
theme = "temple"

[author]
name = "Michael Benfield"
github = "mikebenfield"
email = "mike.benfield@gmail.com"